
use master
go

create database WebApiShop
go

use WebApiShop
go

create table USERS
(
	USER_ID int identity PRIMARY KEY,
	USER_NAME VARCHAR(MAX) NOT NULL,
	PASSWORD VARCHAR(MAX) NOT NULL,
	FIRST_NAME VARCHAR(MAX) NOT NULL,
	LAST_NAME VARCHAR(MAX) NOT NULL,
	ROLE VARCHAR(MAX) NOT NULL DEFAULT 'User'
)

create table CATEGORIES
(
	CATEGORY_ID int identity PRIMARY KEY,
	CATEGORY_NAME VARCHAR(MAX) NOT NULL
)

create table PRODUCTS
(
	PRODUCT_ID int identity PRIMARY KEY,
	PRODUCT_NAME VARCHAR(MAX) NOT NULL,
	PRICE DECIMAL(5,2) NOT NULL,
	CATEGORY_ID int NOT NULL REFERENCES CATEGORIES,
	DESCRIPTION VARCHAR(MAX) NOT NULL
)

create table ORDERS
(
	ORDER_ID int identity PRIMARY KEY,
	ORDER_DATE DATE NOT NULL,
	ORDER_SUM DECIMAL(5,2) NOT NULL,
	USER_ID int NOT NULL REFERENCES USERS
)

create table ORDER_ITEMS
(
	ORDER_ITEM_ID int identity PRIMARY KEY,
	PRODUCT_ID int NOT NULL REFERENCES PRODUCTS,
	ORDER_ID int NOT NULL REFERENCES ORDERS,
	QUANTITY INT NOT NULL
)
