version: '3.8'

services:
  cache-db:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass YourStrongPassword123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge